"""SimulationEngine — the swarm runtime.

Each run plays out in discrete rounds. Active agents act (post / reply /
endorse / dispute), memories and the interaction graph update, factions are
re-detected periodically, and every event is persisted to the run's event
log (the replay source for the timeline scrubber) and broadcast to live
WebSocket subscribers.

Grounding: in live mode, the round's most influential agent's post is
generated by the LLM with its recalled memory + graph context; all other
volume uses the seeded demo generator — this keeps large swarms affordable.
"""
import asyncio
import random
import time
from typing import Any

import networkx as nx

from . import llm
from .demo import (DISPUTE_TEMPLATES, ENDORSE_TEMPLATES, POST_TEMPLATES,
                   REPLY_TEMPLATES, classify_event, pick_template)
from .graphrag import retrieve_context
from .memory import MemoryBank
from .store import store

MAX_BATCH = 50  # max agent actions emitted per round


class RunBus:
    """Persist + fan-out of run events. Backpressure: drop-oldest per subscriber."""

    def __init__(self, run_id: str) -> None:
        self.run_id = run_id
        self.seq = -1  # lazily initialized from the persisted event log
        self.subs: set[asyncio.Queue] = set()

    def publish(self, type_: str, payload: dict) -> int:
        if self.seq < 0:
            # a bus created after a server restart must continue the
            # existing event log, not collide with it
            self.seq = store.max_seq(self.run_id)
        self.seq += 1
        envelope = {"runId": self.run_id, **payload}
        store.append_event(self.run_id, self.seq, type_, envelope)
        msg = {"seq": self.seq, "type": type_, **envelope}
        for q in list(self.subs):
            if q.full():
                try:
                    q.get_nowait()
                except asyncio.QueueEmpty:
                    pass
            try:
                q.put_nowait(msg)
            except asyncio.QueueFull:
                pass
        return self.seq

    def subscribe(self) -> asyncio.Queue:
        q: asyncio.Queue = asyncio.Queue(maxsize=500)
        self.subs.add(q)
        return q

    def unsubscribe(self, q: asyncio.Queue) -> None:
        self.subs.discard(q)


buses: dict[str, RunBus] = {}
engines: dict[str, "SimulationEngine"] = {}


def get_bus(run_id: str) -> RunBus:
    if run_id not in buses:
        buses[run_id] = RunBus(run_id)
    return buses[run_id]


class SimulationEngine:
    def __init__(self, run: dict, project: dict) -> None:
        self.run_meta = run
        self.project = project
        self.personas: list[dict] = project.get("personas") or []
        self.graph: dict = project.get("graph") or {}
        self.labels = [n["label"] for n in self.graph.get("nodes", [])] or ["the situation"]
        self.memory = MemoryBank()
        self.igraph = nx.Graph()
        self.igraph.add_nodes_from(range(len(self.personas)))
        self.scores: dict[str, float] = {p["id"]: 0.0 for p in self.personas}
        self.shocks: list[dict] = []
        self.by_id = {p["id"]: p for p in self.personas}
        self.index_of = {p["id"]: i for i, p in enumerate(self.personas)}
        self.paused = asyncio.Event()
        self.paused.set()
        self.stop_flag = False
        self.control_q: asyncio.Queue = asyncio.Queue()
        self.total_actions = 0
        self.bus = get_bus(run["id"])

    # ── controls (called from API handlers) ──────────────────────────
    async def pause(self) -> None:
        self.paused.clear()
        self._set_status("paused")

    async def resume(self) -> None:
        self.paused.set()
        self._set_status("running")

    async def stop(self) -> None:
        self.stop_flag = True
        self.paused.set()

    async def set_speed(self, speed: float) -> None:
        self.run_meta["speed"] = speed
        self._persist()

    async def inject(self, text: str) -> None:
        await self.control_q.put(("inject", text))

    def _persist(self) -> None:
        store.put_run(self.run_meta)

    def _set_status(self, status: str) -> None:
        self.run_meta["status"] = status
        self._persist()

    # ── helpers ──────────────────────────────────────────────────────
    def _weights(self) -> list[float]:
        return [max(1.0, p["followers"]) ** 0.5 for p in self.personas]

    def _targets(self, rng: random.Random, actor_idx: int) -> list[int]:
        neigh = list(self.igraph.neighbors(actor_idx))
        if neigh and rng.random() < 0.6:
            return [rng.choice(neigh)]
        n = len(self.personas)
        if n < 2:
            return []
        return [rng.choice([i for i in range(n) if i != actor_idx])]

    def _shock_now(self) -> float:
        total = 0.0
        for s in self.shocks:
            total += s["value"] * (s["remaining"] / 5.0)
        return max(-1.0, min(1.0, total))

    def _decay_shocks(self) -> None:
        for s in self.shocks:
            s["remaining"] -= 1
        self.shocks = [s for s in self.shocks if s["remaining"] > 0]

    def _make_action(self, rng: random.Random, idx: int, round_no: int,
                     shock: float, spotlight: bool) -> dict[str, Any]:
        p = self.personas[idx]
        roll = rng.random()
        kind = ("post" if roll < 0.50 else "reply" if roll < 0.75
                else "endorse" if roll < 0.90 else "dispute")
        targets = [] if kind == "post" else self._targets(rng, idx)
        sentiment = max(-1.0, min(1.0,
                                  p["stance"] + shock * p["openness"]
                                  + rng.gauss(0, 0.18)))
        interest = rng.choice(p["interests"]) if p["interests"] else self.labels[0]
        topic = rng.choice(self.labels)
        other = self.personas[targets[0]]["name"] if targets else ""

        text = None
        if spotlight and llm.mode() == "live":
            memory = "\n".join(f"- {m}" for m in self.memory.get(p["id"]).recall()) or "- (start of simulation)"
            context = retrieve_context(self.graph, f"{interest} {topic}")
            text = llm.complete(
                (f'You are {p["name"]}, a {p["archetype"]} in a social simulation. '
                 f'Bio: {p["bio"]} Stance: {p["stance"]:+.2f} (-1 opposed, +1 supportive). '
                 f"Speak in first person, one or two short sentences, plain English, "
                 f"no hashtags, no emojis."),
                (f"World context:\n{context}\n\nYour recent memory:\n{memory}\n\n"
                 f'Write your next public post about "{interest}".'),
                max_tokens=80,
            )
        if not text:
            table = {"post": POST_TEMPLATES, "reply": REPLY_TEMPLATES,
                     "endorse": ENDORSE_TEMPLATES, "dispute": DISPUTE_TEMPLATES}[kind]
            text = pick_template(rng, table, sentiment).format(
                i=interest, t=topic, o=other or "everyone")

        influence = min(1.0, p["followers"] / 10_000.0)
        if targets:
            t_idx = targets[0]
            w = self.igraph[idx][t_idx]["weight"] + 1 if self.igraph.has_edge(idx, t_idx) else 1
            self.igraph.add_edge(idx, t_idx, weight=w)
            tp = self.personas[t_idx]
            self.memory.get(tp["id"]).add(
                f'R{round_no}: {p["name"]} {kind}d me: "{text}"', salient=True)
            td = 0.12 if kind == "dispute" else 0.06
            tp["stance"] = max(-1.0, min(1.0,
                tp["stance"] + td * tp["openness"] * (1 if sentiment > 0 else -1)))
            self.scores[tp["id"]] += 2 if kind in ("endorse", "reply") else 1
        p["stance"] = max(-1.0, min(1.0, p["stance"] + 0.02 * shock * p["openness"]))
        self.memory.get(p["id"]).add(f'R{round_no}: I {kind}ed ("{text}")')
        self.scores[p["id"]] += 1
        self.total_actions += 1
        return {
            "id": f"r{round_no}-{idx}", "agentId": p["id"], "name": p["name"],
            "faction": p.get("faction", 0), "platform": p.get("platform", "Arena A"),
            "action": kind, "sentiment": round(sentiment, 3), "text": text,
            "targets": [self.personas[t]["id"] for t in targets],
            "influence": round(influence, 4), "round": round_no,
            "archetype": p.get("archetype", ""),
        }

    def _metrics(self, round_no: int, actions: list[dict]) -> dict[str, Any]:
        sents = [a["sentiment"] for a in actions]
        avg = sum(sents) / len(sents) if sents else 0.0
        if round_no % 3 == 1 and self.igraph.number_of_edges() > 2:
            try:
                for i, comm in enumerate(
                        nx.community.greedy_modularity_communities(self.igraph, weight="weight")):
                    for n in comm:
                        self.personas[n]["faction"] = i
                self.bus.publish("graph_update", {
                    "round": round_no,
                    "factions": {p["id"]: p.get("faction", 0) for p in self.personas},
                })
            except Exception:
                pass
        shares: dict[str, int] = {}
        for p in self.personas:
            f = str(p.get("faction", 0))
            shares[f] = shares.get(f, 0) + 1
        top = sorted(self.scores.items(), key=lambda kv: -kv[1])[:5]
        return {
            "round": round_no,
            "sentimentAvg": round(avg, 4),
            "activityCount": len(actions),
            "factionShares": {k: round(v / max(1, len(self.personas)), 4)
                              for k, v in shares.items()},
            "topInfluencers": [
                {"id": aid, "name": self.by_id[aid]["name"],
                 "faction": self.by_id[aid].get("faction", 0),
                 "archetype": self.by_id[aid].get("archetype", ""),
                 "score": round(sc, 2)}
                for aid, sc in top
            ],
        }

    async def _drain_controls(self, round_no: int, rng: random.Random) -> None:
        while True:
            try:
                cmd, arg = self.control_q.get_nowait()
            except asyncio.QueueEmpty:
                return
            if cmd == "inject":
                val = classify_event(arg, rng)
                self.shocks.append({"value": val, "remaining": 5})
                for p in self.personas:
                    if rng.random() < 0.35 * p["openness"] + 0.15:
                        p["stance"] = max(-1.0, min(1.0,
                            p["stance"] + val * p["openness"] * 0.4))
                        self.memory.get(p["id"]).add(
                            f'Event: "{arg}" — I reacted {"strongly" if abs(val) > .5 else "mildly"}',
                            salient=True)
                self.bus.publish("event_injected", {"tick": round_no, "text": arg})

    # ── main loop ────────────────────────────────────────────────────
    async def run(self) -> None:
        rounds = self.run_meta["rounds"]
        self._set_status("running")
        try:
            for r in range(1, rounds + 1):
                if self.stop_flag:
                    self._finish(r - 1, stopped=True)
                    return
                await self.paused.wait()
                rng = random.Random(self.run_meta["seed"] * 1_000_003 + r)
                await self._drain_controls(r, rng)
                shock = self._shock_now()

                self.run_meta["round"] = r
                self.bus.publish("round_started", {"round": r, "rounds": rounds})

                n_active = min(MAX_BATCH, max(8, int(0.3 * len(self.personas))))
                picks = rng.choices(range(len(self.personas)),
                                    weights=self._weights(), k=n_active * 2)
                seen, active = set(), []
                for i in picks:
                    if i not in seen:
                        seen.add(i)
                        active.append(i)
                    if len(active) >= n_active:
                        break
                spotlight_idx = max(active, key=lambda i: self.personas[i]["followers"]) if active else -1
                actions = [
                    self._make_action(rng, i, r, shock, spotlight=(i == spotlight_idx))
                    for i in active
                ]
                self.bus.publish("round_batch", {"round": r, "actions": actions})
                self.bus.publish("metrics", self._metrics(r, actions))
                self._persist()
                self._decay_shocks()
                await asyncio.sleep(min(2.0, max(0.01, 1.0 / float(self.run_meta["speed"]))))
            self._finish(rounds, stopped=False)
        except Exception as e:
            self._set_status("failed")
            self.bus.publish("error", {"message": f"simulation failed: {e}"})

    def _finish(self, last_round: int, stopped: bool) -> None:
        self.run_meta["round"] = last_round
        sents_final = [
            a["sentiment"] for a in
            self._last_actions(last_round)
        ] or [0.0]
        factions: dict[str, int] = {}
        for p in self.personas:
            factions[str(p.get("faction", 0))] = factions.get(str(p.get("faction", 0)), 0) + 1
        summary = {
            "rounds": last_round,
            "totalActions": self.total_actions,
            "finalSentiment": round(sum(sents_final) / len(sents_final), 4),
            "factionCount": len(factions),
            "stopped": stopped,
            "personas": self.personas,
        }
        self.run_meta["summary"] = summary
        self._set_status("stopped" if stopped else "complete")
        self.bus.publish("run_complete", {"summary": {k: v for k, v in summary.items() if k != "personas"}})

    def _last_actions(self, up_to_round: int) -> list[dict]:
        out: list[dict] = []
        for ev in store.events_after(self.run_meta["id"]):
            if ev["type"] == "round_batch" and ev.get("round", 0) <= up_to_round:
                out.extend(ev.get("actions", []))
        return out[-400:]


async def start_engine(run: dict, project: dict) -> SimulationEngine:
    engine = SimulationEngine(run, project)
    engines[run["id"]] = engine
    store.put_run(run)
    asyncio.create_task(engine.run())
    return engine
