#!/usr/bin/env python3
"""One-shot English sweep for backend/scripts/run_reddit_simulation.py."""
import re

P = "backend/scripts/run_reddit_simulation.py"
src = open(P, encoding="utf-8").read()

M = {
    "OASIS Reddit模拟预设脚本": "OASIS Reddit simulation preset script",
    "此脚本读取配置文件中的参数来执行模拟，实现全程自动化": "Reads parameters from the config file to run the simulation fully automated.",
    "功能特性:": "Features:",
    "- 完成模拟后不立即关闭环境，进入等待命令模式": "- Keeps the environment open after the simulation finishes (wait-for-commands mode)",
    "- 支持通过IPC接收Interview命令": "- Receives Interview commands over IPC",
    "- 支持单个Agent采访和批量采访": "- Supports single-agent and batch interviews",
    "- 支持远程关闭环境命令": "- Supports the remote close-environment command",
    "使用方式:": "Usage:",
    "完成后立即关闭": "close immediately when done",
    "# 全局变量：用于信号处理": "# globals for signal handling",
    "# 添加项目路径": "# add the project path",
    "# 加载项目根目录的 .env 文件（包含 LLM_API_KEY 等配置）": "# load the repo-root .env file (LLM_API_KEY etc.)",
    "自定义格式化器，将 Unicode 转义序列转换为可读字符": "Formatter that turns Unicode escape sequences into readable characters.",
    "过滤掉 camel-ai 关于 max_tokens 的警告（我们故意不设置 max_tokens，让模型自行决定）": "Filter camel-ai max_tokens warnings (we intentionally omit max_tokens; the model decides).",
    "过滤掉包含 max_tokens 警告的日志": "drop log records mentioning max_tokens",
    "在模块加载时立即添加过滤器，确保在 camel 代码执行前生效": "# install the filter at import time so it applies before camel code runs",
    "配置 OASIS 的日志，使用固定名称的日志文件": "Configure OASIS logging with fixed log file names.",
    "清理旧的日志文件": "remove stale log files",
    "错误: 缺少依赖 {e}": "Error: missing dependency {e}",
    "请先安装: pip install oasis-ai camel-ai": "Install first: pip install oasis-ai camel-ai",
    "# IPC相关常量": "# IPC constants",
    "命令类型常量": "Command type constants.",
    "IPC命令处理器": "IPC command handler.",
    "# 确保目录存在": "        # make sure the directory exists",
    "更新环境状态": "        Update the environment status.",
    "轮询获取待处理命令": "        Poll for pending commands.",
    "# 获取命令文件（按时间排序）": "        # command files sorted by time",
    "发送响应": "        Send a response.",
    "# 删除命令文件": "        # delete the command file",
    "处理单个Agent采访命令": "        Handle a single-agent interview command.",
    " True 表示成功，False 表示失败": "            True on success, False on failure",
    "# 获取Agent": "            # fetch the agent",
    "# 创建Interview动作": "            # build the Interview action",
    "# 执行Interview": "            # run the Interview",
    "# 从数据库获取结果": "            # read the result from the database",
    "Interview完成: agent_id={agent_id}": "Interview finished: agent_id={agent_id}",
    "Interview失败: agent_id={agent_id}, error={error_msg}": "Interview failed: agent_id={agent_id}, error={error_msg}",
    "处理批量采访命令": "        Handle a batch-interview command.",
    "# 构建动作字典": "            # build the action dict",
    "# 记录每个agent的prompt": "per-agent prompts",
    "警告: 无法获取Agent {agent_id}: {e}": "Warning: cannot fetch agent {agent_id}: {e}",
    "没有有效的Agent": "No valid agents",
    "# 执行批量Interview": "            # run the batch Interview",
    "# 获取所有结果": "            # collect all results",
    "批量Interview完成: {len(results)} 个Agent": "Batch Interview finished: {len(results)} agents",
    "批量Interview失败: {error_msg}": "Batch Interview failed: {error_msg}",
    "从数据库获取最新的Interview结果": "        Get the latest Interview result from the database.",
    "# 查询最新的Interview记录": "            # query the newest Interview record",
    "读取Interview结果失败: {e}": "Failed to read Interview result: {e}",
    "处理所有待处理命令": "        Process all pending commands.",
    " True 表示继续运行，False 表示应该退出": "            True to keep running, False to exit",
    "收到IPC命令: {command_type}, id={command_id}": "IPC command received: {command_type}, id={command_id}",
    "收到关闭环境命令": "Close-environment command received",
    "环境即将关闭": "Environment closing",
    "未知命令类型: {command_type}": "Unknown command type: {command_type}",
    "Reddit模拟运行器": "Reddit simulation runner.",
    "# Reddit可用动作（不包含INTERVIEW，INTERVIEW只能通过ManualAction手动触发）": "    # available Reddit actions (no INTERVIEW; interviews run via ManualAction only)",
    "初始化模拟运行器": "        Initialize the simulation runner.",
    "config_path: 配置文件路径 (simulation_config.json)": "            config_path: config file path (simulation_config.json)",
    "wait_for_commands: 模拟完成后是否等待命令（默认True）": "            wait_for_commands: keep waiting for commands after finishing (default True)",
    "加载配置文件": "        Load the config file.",
    "获取Profile文件路径": "        Get the profile file path.",
    "获取数据库路径": "        Get the database path.",
    "创建LLM模型": "        Create the LLM model.",
    "统一使用项目根目录 .env 文件中的配置（优先级最高）：": "        Config comes from the repo-root .env file (highest priority):",
    "- LLM_API_KEY: API密钥": "        - LLM_API_KEY: API key",
    "- LLM_BASE_URL: API基础URL": "        - LLM_BASE_URL: API base URL",
    "- LLM_MODEL_NAME: 模型名称": "        - LLM_MODEL_NAME: model name",
    "# 优先从 .env 读取配置": "        # prefer .env values",
    "# 如果 .env 中没有，则使用 config 作为备用": "        # fall back to the config file when absent from .env",
    "# 设置 camel-ai 所需的环境变量": "        # env vars camel-ai expects",
    "缺少 API Key 配置，请在项目根目录 .env 文件中设置 LLM_API_KEY": "Missing API key: set LLM_API_KEY in the repo-root .env file",
    "LLM配置: model={llm_model}, base_url={llm_base_url[:40] if llm_base_url else '默认'}...": "LLM config: model={llm_model}, base_url={llm_base_url[:40] if llm_base_url else 'default'}...",
    "根据时间和配置决定本轮激活哪些Agent": "        Decide which agents activate this round based on time and config.",
    "env: OASIS环境": "            env: the OASIS environment",
    "current_hour: 当前模拟小时（0-23）": "            current_hour: simulated hour of day (0-23)",
    "round_num: 当前轮数": "            round_num: current round",
    "激活的Agent列表": "            The list of activated agents.",
    "# 基础激活数量": "        # base activation count",
    "# 根据时段调整": "        # adjust for the time of day",
    "# 根据每个Agent的配置计算激活概率": "        # per-agent activation probability from config",
    "# 检查是否在活跃时间": "            # inside the active hours?",
    "# 根据活跃度计算概率": "            # probability from the activity level",
    "# 随机选择": "        # random selection",
    "# 转换为Agent对象": "        # convert to Agent objects",
    "运行Reddit模拟": "        Run the Reddit simulation.",
    "max_rounds: 最大模拟轮数（可选，用于截断过长的模拟）": "            max_rounds: max rounds (optional; truncates over-long simulations)",
    "OASIS Twitter模拟": "OASIS Twitter simulation",
    "配置文件: {self.config_path}": "Config file: {self.config_path}",
    "模拟ID: {self.config.get('simulation_id', 'unknown')}": "Simulation ID: {self.config.get('simulation_id', 'unknown')}",
    "等待命令模式: {'启用' if self.wait_for_commands else '禁用'}": "Wait-for-commands mode: {'enabled' if self.wait_for_commands else 'disabled'}",
    "# 加载时间配置": "        # load the time config",
    "# 计算总轮数": "        # compute total rounds",
    "# 如果指定了最大轮数，则截断": "        # truncate when max rounds given",
    "轮数已截断: {original_rounds} -> {total_rounds} (max_rounds={max_rounds})": "Rounds truncated: {original_rounds} -> {total_rounds} (max_rounds={max_rounds})",
    "模拟参数:": "Simulation parameters:",
    "  - 总模拟时长: {total_hours}小时": "  - Total simulated time: {total_hours}h",
    "  - 每轮时间: {minutes_per_round}分钟": "  - Time per round: {minutes_per_round} min",
    "  - 总轮数: {total_rounds}": "  - Total rounds: {total_rounds}",
    "  - 最大轮数限制: {max_rounds}": "  - Max rounds cap: {max_rounds}",
    "  - Agent数量: {len(self.config.get('agent_configs', []))}": "  - Agents: {len(self.config.get('agent_configs', []))}",
    "# 创建模型": "        # create the model",
    "初始化LLM模型...": "Initializing LLM model...",
    "# 加载Agent图": "        # load the agent graph",
    "加载Agent Profile...": "Loading agent profiles...",
    "错误: Profile文件不存在: {profile_path}": "Error: profile file not found: {profile_path}",
    "# 数据库路径": "        # database path",
    "已删除旧数据库: {db_path}": "Removed stale database: {db_path}",
    "# 创建环境": "        # create the environment",
    "创建OASIS环境...": "Creating OASIS environment...",
    "限制最大并发 LLM 请求数，防止 API 过载": "cap concurrent LLM requests to avoid API overload",
    "环境初始化完成": "Environment ready",
    "# 初始化IPC处理器": "        # initialize the IPC handler",
    "# 执行初始事件": "        # run the initial events",
    "执行初始事件 ({len(initial_posts)}条初始帖子)...": "Running initial events ({len(initial_posts)} initial posts)...",
    "警告: 无法为Agent {agent_id}创建初始帖子: {e}": "Warning: cannot create the initial post for agent {agent_id}: {e}",
    "已发布 {len(initial_actions)} 条初始帖子": "Published {len(initial_actions)} initial posts",
    "# 主模拟循环": "        # main simulation loop",
    "开始模拟循环...": "Starting simulation loop...",
    "# 计算当前模拟时间": "            # current simulated time",
    "# 获取本轮激活的Agent": "            # agents activated this round",
    "# 构建动作": "            # build actions",
    "# 执行动作": "            # perform actions",
    "# 打印进度": "            # progress printout",
    "模拟循环完成!": "Simulation loop finished!",
    "  - 总耗时: {total_elapsed:.1f}秒": "  - Elapsed: {total_elapsed:.1f}s",
    "  - 数据库: {db_path}": "  - Database: {db_path}",
    "# 是否进入等待命令模式": "        # enter wait-for-commands mode?",
    "进入等待命令模式 - 环境保持运行": "Entering wait-for-commands mode - environment stays up",
    "支持的命令: interview, batch_interview, close_env": "Supported commands: interview, batch_interview, close_env",
    "# 等待命令循环（使用全局 _shutdown_event）": "            # command wait loop (global _shutdown_event)",
    "收到退出信号": "exit signal received",
    "收到中断信号": "Interrupt signal received",
    "任务被取消": "Task cancelled",
    "命令处理出错: {e}": "Command handling error: {e}",
    "关闭环境...": "Closing environment...",
    "# 关闭环境": "        # close the environment",
    "环境已关闭": "Environment closed",
    "OASIS Twitter模拟'": "OASIS Reddit simulation'",
    "配置文件路径 (simulation_config.json)": "config file path (simulation_config.json)",
    "最大模拟轮数（可选，用于截断过长的模拟）": "max simulation rounds (optional; truncates over-long simulations)",
    "模拟完成后立即关闭环境，不进入等待命令模式": "close the environment right after the simulation (no wait-for-commands)",
    "# 在 main 函数开始时创建 shutdown 事件": "    # create the shutdown event at the start of main",
    "错误: 配置文件不存在: {args.config}": "Error: config file not found: {args.config}",
    "# 初始化日志配置（使用固定文件名，清理旧日志）": "    # logging setup (fixed names; stale logs removed)",
    "设置信号处理器，确保收到 SIGTERM/SIGINT 时能够正确退出": "Install signal handlers so SIGTERM/SIGINT exit cleanly.",
    "让程序有机会正常清理资源（关闭数据库、环境等）": "Gives the program a chance to release resources (databases, environment, ...).",
    "收到 {sig_name} 信号，正在退出...": "{sig_name} received; exiting...",
    "# 重复收到信号才强制退出": "second signal forces the exit",
    "强制退出...": "Forcing exit...",
    "程序被中断": "Program interrupted",
    "模拟进程已退出": "Simulation process exited",
}

keys = sorted(M.keys(), key=len, reverse=True)
lines = src.splitlines(keepends=True)
ok = miss = 0
for i, line in enumerate(lines):
    if not re.search(r"[\u4e00-\u9fff]", line):
        continue
    body = line.rstrip("\n")
    for zh in keys:
        if zh in body:
            body = body.replace(zh, M[zh])
            ok += 1
            break
    else:
        miss += 1
        print(f"MISS {i+1}: {body.strip()[:70]}")
    lines[i] = body + "\n"
open(P, "w", encoding="utf-8").write("".join(lines))
cjk = sum(1 for l in lines if re.search(r"[\u4e00-\u9fff]", l))
print(f"twitter: {ok} ok, {miss} miss, {cjk} left")
