#!/usr/bin/env python3
"""One-shot English sweep for backend/app/services/simulation_runner.py."""
import re

P = "backend/app/services/simulation_runner.py"
src = open(P, encoding="utf-8").read()
src = src.replace(
    "from .services.analytics import run_analytics_async",
    "from .analytics import run_analytics_async",
)

M = {
    "OASIS模拟运行器": "OASIS simulation runner",
    "在后台运行模拟并记录每个Agent的动作，支持实时状态监控": "Runs simulations in a background process, records every agent action, and supports real-time status monitoring",
    "标记是否已注册清理函数": "flag: cleanup handler already registered",
    "平台检测": "platform detection",
    "运行器状态": "Runner status",
    "Agent动作记录": "A recorded agent action",
    "每轮摘要": "Per-round summary",
    "模拟运行状态（实时）": "Live simulation run state",
    "进度信息": "progress info",
    "各平台独立轮次和模拟时间（用于双平台并行显示）": "per-platform round count and simulated time (for dual-platform parallel display)",
    "平台状态": "platform status",
    "平台完成状态（通过检测 actions.jsonl 中的 simulation_end 事件）": "platform completion (detected via simulation_end events in actions.jsonl)",
    "最近动作（用于前端实时展示）": "recent actions (for real-time frontend display)",
    "时间戳": "timestamps",
    "错误信息": "error message",
    "进程ID（用于停止）": "process id (for stopping)",
    "添加动作到最近动作列表": "        Add an action to the recent-actions list.",
    "各平台独立轮次和时间": "per-platform rounds and time",
    "包含最近动作的详细信息": "        Detailed info including recent actions.",
    "模拟运行器": "    Simulation runner.",
    "负责：": "    Responsibilities:",
    "在后台进程中运行OASIS模拟": "    1. Run the OASIS simulation in a background process",
    "解析运行日志，记录每个Agent的动作": "    2. Parse run logs and record every agent action",
    "提供实时状态查询接口": "    3. Expose real-time status queries",
    "支持暂停/停止/恢复操作": "    4. Support pause/stop/resume operations",
    "运行状态存储目录": "    # directory for run-state storage",
    "脚本目录": "    # scripts directory",
    "内存中的运行状态": "    # in-memory run states",
    "存储 stdout 文件句柄": "stdout file handles",
    "存储 stderr 文件句柄": "stderr file handles",
    "图谱记忆更新配置": "    # graph-memory update configuration",
    "同步模拟状态失败: simulation_id=%s, status=%s, error=%s": "Failed to sync simulation state: simulation_id=%s, status=%s, error=%s",
    "获取运行状态": "        Get the run state.",
    "尝试从文件加载": "        # try loading from file",
    "从文件加载运行状态": "        Load the run state from file.",
    "加载运行状态失败: {str(e)}": "Failed to load run state: {str(e)}",
    "保存运行状态到文件": "        Save the run state to file.",
    "最大模拟轮数（可选，用于截断过长的模拟）": "max simulation rounds (optional; truncates over-long simulations)",
    "是否将活动更新到Zep图谱": "whether to push activity updates to the Zep graph",
    "Zep图谱ID（启用图谱更新时必需）": "Zep graph id (required when graph updates are enabled)",
    "启动模拟": "        Start the simulation.",
    "simulation_id: 模拟ID": "            simulation_id: simulation id",
    "platform: 运行平台 (twitter/reddit/parallel)": "            platform: platform to run (twitter/reddit/parallel)",
    "enable_graph_memory_update: 是否将Agent活动动态更新到Zep图谱": "            enable_graph_memory_update: whether to stream agent activity to the Zep graph",
    "graph_id: Zep图谱ID（启用图谱更新时必需）": "            graph_id: Zep graph id (required when graph updates are enabled)",
    "加载模拟配置": "        # load the simulation config",
    "模拟配置不存在，请先调用 /prepare 接口": "Simulation config not found; call the /prepare endpoint first",
    "初始化运行状态": "        # initialize the run state",
    "如果指定了最大轮数，则截断": "        # truncate if a max round count was given",
    "轮数已截断: {original_rounds} -> {total_rounds} (max_rounds={max_rounds})": "Rounds truncated: {original_rounds} -> {total_rounds} (max_rounds={max_rounds})",
    "模拟已在运行或结束处理中: {simulation_id}": "Simulation already running or finishing: {simulation_id}",
    "如果启用图谱记忆更新，创建更新器": "        # create the graph-memory updater if enabled",
    "启用图谱记忆更新时必须提供 graph_id": "graph_id is required when graph memory update is enabled",
    "已启用图谱记忆更新: simulation_id={simulation_id}, graph_id={graph_id}": "Graph memory update enabled: simulation_id={simulation_id}, graph_id={graph_id}",
    "创建图谱记忆更新器失败: {e}": "Failed to create graph memory updater: {e}",
    "Zep图谱更新器初始化失败: {e}": "Zep graph updater initialization failed: {e}",
    "确定运行哪个脚本（脚本位于 backend/scripts/ 目录）": "        # pick the runner script (lives in backend/scripts/)",
    "脚本不存在: {script_path}": "Script not found: {script_path}",
    "Zep图谱写入清理失败: {cleanup_error}": "Zep graph write cleanup failed: {cleanup_error}",
    "Zep图谱写入清理失败: {error}": "Zep graph write cleanup failed: {error}",
    "创建动作队列": "        # create the action queue",
    "启动模拟进程": "        # launch the simulation process",
    "构建运行命令，使用完整路径": "            # build the run command with absolute paths",
    "新的日志结构：": "            # new log layout:",
    "twitter/actions.jsonl - Twitter 动作日志": "            #   twitter/actions.jsonl - Twitter action log",
    "reddit/actions.jsonl  - Reddit 动作日志": "            #   reddit/actions.jsonl  - Reddit action log",
    "simulation.log        - 主进程日志": "            #   simulation.log        - main process log",
    "Python解释器": "Python interpreter",
    "使用完整配置文件路径": "full config file path",
    "如果指定了最大轮数，添加到命令行参数": "            # append max rounds to the command line if given",
    "创建主日志文件，避免 stdout/stderr 管道缓冲区满导致进程阻塞": "            # main log file: avoids the child blocking on full stdout/stderr pipe buffers",
    "设置子进程环境变量，确保 Windows 上使用 UTF-8 编码": "            # child env vars: force UTF-8 on Windows",
    "这可以修复第三方库（如 OASIS）读取文件时未指定编码的问题": "            # fixes third-party libs (e.g. OASIS) reading files without an explicit encoding",
    "Python 3.7+ 支持，让所有 open() 默认使用 UTF-8": "Python 3.7+: all open() calls default to UTF-8",
    "确保 stdout/stderr 使用 UTF-8": "force UTF-8 on stdout/stderr",
    "设置工作目录为模拟目录（数据库等文件会生成在此）": "            # cwd = simulation dir (databases etc. are created there)",
    "使用 start_new_session=True 创建新的进程组，确保可以通过 os.killpg 终止所有子进程": "            # start_new_session=True creates a new process group so os.killpg can stop every child",
    "stderr 也写入同一个文件": "stderr goes to the same file",
    "显式指定编码": "explicit encoding",
    "传递带有 UTF-8 设置的环境变量": "env with UTF-8 settings",
    "创建新进程组，确保服务器关闭时能终止所有相关进程": "new process group so server shutdown can stop all children",
    "模拟启动成功: {simulation_id}, pid={process.pid}, platform={platform}": "Simulation started: {simulation_id}, pid={process.pid}, platform={platform}",
    "子进程终止失败: {error}": "Failed to terminate child process: {error}",
    "日志关闭失败: {error}": "Failed to close log file: {error}",
    "监控模拟进程，解析动作日志": "Monitor the simulation process and parse action logs.",
    "新的日志结构：分平台的动作日志": "        # new log layout: per-platform action logs",
    "进程仍在运行": "process still running",
    "读取 Twitter 动作日志": "                # read the Twitter action log",
    "读取 Reddit 动作日志": "                # read the Reddit action log",
    "更新状态": "                # update state",
    "进程结束后，最后读取一次日志": "            # final log read after the process exits",
    "监控线程异常: {simulation_id}, error={str(e)}": "Monitor thread error: {simulation_id}, error={str(e)}",
    "进程退出码: {exit_code}, 错误: {error_info}": "Process exit code: {exit_code}, error: {error_info}",
    "已停止图谱记忆更新: simulation_id=%s": "Stopped graph memory updates: simulation_id=%s",
    "停止图谱记忆更新器失败: {error}": "Failed to stop graph memory updater: {error}",
    "Zep图谱写入未完整完成: {error}": "Zep graph write did not complete: {error}",
    "模拟完成: {simulation_id}": "Simulation finished: {simulation_id}",
    "分析管线已排队: {simulation_id}": "Analytics pipeline queued: {simulation_id}",
    "分析管线排队失败: {simulation_id}, ": "Analytics pipeline enqueue failed: {simulation_id}, ",
    "模拟失败: {simulation_id}, error={state.error}": "Simulation failed: {simulation_id}, error={state.error}",
    "清理进程资源": "            # release process resources",
    "关闭日志文件句柄": "            # close log file handles",
    "读取动作日志文件": "        Read an action log file.",
    "log_path: 日志文件路径": "            log_path: path to the log file",
    "position: 上次读取位置": "            position: previous read offset",
    "state: 运行状态对象": "            state: run-state object",
    "platform: 平台名称 (twitter/reddit)": "            platform: platform name (twitter/reddit)",
    "新的读取位置": "            The new read offset.",
    "检查是否启用了图谱记忆更新": "        # is graph memory updating enabled?",
    "处理事件类型的条目": "                            # handle event-type entries",
    "检测 simulation_end 事件，标记平台已完成": "                                # simulation_end event marks a platform as finished",
    "Twitter 模拟已完成: {state.simulation_id}, total_rounds={action_data.get('total_rounds')}, total_actions={action_data.get('total_actions')}": "Twitter simulation finished: {state.simulation_id}, total_rounds={action_data.get('total_rounds')}, total_actions={action_data.get('total_actions')}",
    "Reddit 模拟已完成: {state.simulation_id}, total_rounds={action_data.get('total_rounds')}, total_actions={action_data.get('total_actions')}": "Reddit simulation finished: {state.simulation_id}, total_rounds={action_data.get('total_rounds')}, total_actions={action_data.get('total_actions')}",
    "检查是否所有启用的平台都已完成": "                                    # all enabled platforms finished?",
    "如果只运行了一个平台，只检查那个平台": "                                    # single-platform run: check that platform only",
    "如果运行了两个平台，需要两个都完成": "                                    # dual-platform run: both must finish",
    "所有平台已结束，等待进程与图谱写入完成: ": "All platforms finished; waiting for process and graph writes: ",
    "更新轮次信息（从 round_end 事件）": "                                # update round info (from round_end events)",
    "更新各平台独立的轮次和时间": "                                    # per-platform rounds and time",
    "总体轮次取两个平台的最大值": "                                    # overall rounds = max across platforms",
    "总体时间取两个平台的最大值": "                                    # overall time = max across platforms",
    "更新轮次": "                            # update round counter",
    "如果启用了图谱记忆更新，将活动发送到Zep": "                            # push activity to Zep when graph memory updating is on",
    "读取动作日志失败: {log_path}, error={e}": "Failed to read action log: {log_path}, error={e}",
    "检查所有启用的平台是否都已完成模拟": "        Check whether every enabled platform finished its simulation.",
    "通过检查对应的 actions.jsonl 文件是否存在来判断平台是否被启用": "        A platform counts as enabled when its actions.jsonl exists.",
    " True 如果所有启用的平台都已完成": "            True when all enabled platforms finished",
    "检查哪些平台被启用（通过文件是否存在判断）": "        # which platforms are enabled (by file existence)",
    "如果平台被启用但未完成，则返回 False": "        # enabled but not finished -> False",
    "至少有一个平台被启用且已完成": "        # at least one platform enabled and finished",
    "跨平台终止进程及其子进程": "        Terminate a process tree across platforms.",
    "process: 要终止的进程": "            process: process to terminate",
    "simulation_id: 模拟ID（用于日志）": "            simulation_id: simulation id (for logging)",
    "timeout: 等待进程退出的超时时间（秒）": "            timeout: seconds to wait for exit",
    "Windows: 使用 taskkill 命令终止进程树": "            # Windows: taskkill the whole process tree",
    "/F = 强制终止, /T = 终止进程树（包括子进程）": "            # /F = force, /T = tree (includes children)",
    "终止进程树 (Windows): simulation={simulation_id}, pid={process.pid}": "Terminating process tree (Windows): simulation={simulation_id}, pid={process.pid}",
    "先尝试优雅终止": "                    # try graceful first",
    "强制终止": "                    # force kill",
    "进程未响应，强制终止: {simulation_id}": "Process unresponsive, force killing: {simulation_id}",
    "taskkill 失败，尝试 terminate: {e}": "taskkill failed, falling back to terminate: {e}",
    "Unix: 使用进程组终止": "            # Unix: kill the process group",
    "由于使用了 start_new_session=True，进程组 ID 等于主进程 PID": "            # with start_new_session=True the pgid equals the main PID",
    "终止进程组 (Unix): simulation={simulation_id}, pgid={pgid}": "Terminating process group (Unix): simulation={simulation_id}, pgid={pgid}",
    "先发送 SIGTERM 给整个进程组": "            # SIGTERM the whole group first",
    "如果超时后还没结束，强制发送 SIGKILL": "                # still alive after timeout: send SIGKILL",
    "进程组未响应 SIGTERM，强制终止: {simulation_id}": "Process group ignored SIGTERM, force killing: {simulation_id}",
    "停止模拟": "        Stop the simulation.",
    "模拟不存在: {simulation_id}": "Simulation not found: {simulation_id}",
    "模拟未在运行: {simulation_id}, status={state.runner_status}": "Simulation not running: {simulation_id}, status={state.runner_status}",
    "终止进程": "            # terminate the process",
    "终止进程组失败: {simulation_id}, error={e}": "Failed to kill process group: {simulation_id}, error={e}",
    "模拟仍在停止中，图谱写入未在 {wait_timeout:.0f}s 内完成": "Simulation still stopping; graph writes did not finish within {wait_timeout:.0f}s",
    "模拟停止失败": "Failed to stop the simulation",
    "模拟停止未达到终态: {simulation_id}, status={state.runner_status}": "Stop did not reach a terminal state: {simulation_id}, status={state.runner_status}",
    "模拟已停止: {simulation_id}": "Simulation stopped: {simulation_id}",
    "从单个动作文件中读取动作": "        Read actions from a single action file.",
    "file_path: 动作日志文件路径": "            file_path: action log file path",
    "default_platform: 默认平台（当动作记录中没有 platform 字段时使用）": "            default_platform: fallback when a record has no platform field",
    "platform_filter: 过滤平台": "            platform_filter: platform filter",
    "agent_id: 过滤 Agent ID": "            agent_id: agent-id filter",
    "round_num: 过滤轮次": "            round_num: round filter",
    "跳过非动作记录（如 simulation_start, round_start, round_end 等事件）": "                    # skip non-action records (simulation_start, round_start, round_end, ...)",
    "跳过没有 agent_id 的记录（非 Agent 动作）": "                    # skip records without agent_id (not agent actions)",
    "获取平台：优先使用记录中的 platform，否则使用默认平台": "                    # platform: record field first, else the default",
    "过滤": "                    # filtering",
    "获取所有平台的完整动作历史（无分页限制）": "        Get the full action history across platforms (no pagination).",
    "platform: 过滤平台（twitter/reddit）": "            platform: platform filter (twitter/reddit)",
    "agent_id: 过滤Agent": "            agent_id: agent filter",
    "完整的动作列表（按时间戳排序，新的在前）": "            Full action list sorted by timestamp, newest first.",
    "读取 Twitter 动作文件（根据文件路径自动设置 platform 为 twitter）": "        # read the Twitter action file (platform inferred from path)",
    "自动填充 platform 字段": "auto-fill the platform field",
    "读取 Reddit 动作文件（根据文件路径自动设置 platform 为 reddit）": "        # read the Reddit action file (platform inferred from path)",
    "如果分平台文件不存在，尝试读取旧的单一文件格式": "        # fall back to the legacy single-file layout",
    "旧格式文件中应该有 platform 字段": "legacy files carry their own platform field",
    "按时间戳排序（新的在前）": "        # sort by timestamp (newest first)",
    "获取动作历史（带分页）": "        Get the action history (paginated).",
    "limit: 返回数量限制": "            limit: max items to return",
    "offset: 偏移量": "            offset: pagination offset",
    "动作列表": "            The action list.",
    "分页": "        # pagination",
    "获取模拟时间线（按轮次汇总）": "        Get the simulation timeline (grouped by round).",
    "start_round: 起始轮次": "            start_round: first round",
    "end_round: 结束轮次": "            end_round: last round",
    "每轮的汇总信息": "            Per-round summary info.",
    "按轮次分组": "        # group by round",
    "转换为列表": "        # convert to a list",
    "获取每个Agent的统计信息": "        Get per-agent statistics.",
    "Agent统计列表": "            Per-agent stats list.",
    "按总动作数排序": "        # sort by total action count",
    "清理模拟的运行日志（用于强制重新开始模拟）": "        Clean a simulation's run logs (to force a fresh restart).",
    "会删除以下文件：": "        Deletes:",
    "twitter_simulation.db（模拟数据库）": "        - twitter_simulation.db (simulation database)",
    "reddit_simulation.db（模拟数据库）": "        - reddit_simulation.db (simulation database)",
    "env_status.json（环境状态）": "        - env_status.json (environment status)",
    "注意：不会删除配置文件（simulation_config.json）和 profile 文件": "        Note: config (simulation_config.json) and profile files are kept.",
    "清理结果信息": "            Cleanup result details.",
    "模拟目录不存在，无需清理": "Simulation directory missing; nothing to clean",
    "要删除的文件列表（包括数据库文件）": "        # files to delete (incl. databases)",
    "Twitter 平台数据库": "Twitter platform database",
    "Reddit 平台数据库": "Reddit platform database",
    "环境状态文件": "environment status file",
    "要删除的目录列表（包含动作日志）": "        # directories to delete (action logs)",
    "删除文件": "        # delete files",
    "删除 {filename} 失败: {str(e)}": "Failed to delete {filename}: {str(e)}",
    "清理平台目录中的动作日志": "        # clean action logs inside platform dirs",
    "删除 {dir_name}/actions.jsonl 失败: {str(e)}": "Failed to delete {dir_name}/actions.jsonl: {str(e)}",
    "清理内存中的运行状态": "        # drop the in-memory run state",
    "清理模拟日志完成: {simulation_id}, 删除文件: {cleaned_files}": "Log cleanup done: {simulation_id}, files removed: {cleaned_files}",
    "防止重复清理的标志": "    # guard against duplicate cleanup",
    "清理所有运行中的模拟进程": "        Clean up every running simulation process.",
    "在服务器关闭时调用，确保所有子进程被终止": "        Called on server shutdown so all children are terminated.",
    "防止重复清理": "        # re-entry guard",
    "正在安全完成所有模拟进程与图谱写入...": "Safely finishing all simulation processes and graph writes...",
    "清理模拟失败，保留状态以便重试: simulation_id=%s, error=%s": "Simulation cleanup failed; state kept for retry: simulation_id=%s, error=%s",
    "部分模拟未安全完成清理": "Some simulations did not shut down cleanly",
    "模拟进程与图谱写入清理完成": "Simulation processes and graph writes cleaned up",
    "注册清理函数": "        Register cleanup handlers.",
    "在 Flask 应用启动时调用，确保服务器关闭时清理所有模拟进程": "        Call at Flask startup so shutdown cleans every simulation.",
    "Flask debug 模式下，只在 reloader 子进程中注册清理（实际运行应用的进程）": "        # Flask debug: register in the reloader child only (the process running the app)",
    "WERKZEUG_RUN_MAIN=true 表示是 reloader 子进程": "        # WERKZEUG_RUN_MAIN=true marks the reloader child",
    "如果不是 debug 模式，则没有这个环境变量，也需要注册": "        # non-debug runs lack that env var and must register too",
    "在 debug 模式下，只在 reloader 子进程中注册；非 debug 模式下始终注册": "        # debug: reloader child only; non-debug: always",
    "标记已注册，防止子进程再次尝试": "mark registered so children do not retry",
    "保存原有的信号处理器": "        # keep the original signal handlers",
    "SIGHUP 只在 Unix 系统存在（macOS/Linux），Windows 没有": "        # SIGHUP exists only on Unix (macOS/Linux), not Windows",
    "信号处理器：先清理模拟进程，再调用原处理器": "Signal handler: clean up simulations, then invoke the original handler.",
    "只有在有进程需要清理时才打印日志": "            # log only when something actually needs cleaning",
    "收到信号 {signum}，开始清理...": "Signal {signum} received; cleaning up...",
    "调用原有的信号处理器，让 Flask 正常退出": "            # call the original handler so Flask exits normally",
    "SIGHUP: 终端关闭时发送": "                # SIGHUP: terminal closed",
    "默认行为：正常退出": "                    # default: exit normally",
    "如果原处理器不可调用（如 SIG_DFL），则使用默认行为": "                    # original handler not callable (e.g. SIG_DFL) -> default",
    "注册 atexit 处理器（作为备用）": "        # atexit handler as a fallback",
    "注册信号处理器（仅在主线程中）": "        # register signal handlers (main thread only)",
    "SIGTERM: kill 命令默认信号": "            # SIGTERM: default signal of kill",
    "SIGHUP: 终端关闭（仅 Unix 系统）": "            # SIGHUP: terminal closed (Unix only)",
    "不在主线程中，只能使用 atexit": "            # not the main thread: atexit only",
    "无法注册信号处理器（不在主线程），仅使用 atexit": "Cannot register signal handlers (not the main thread); using atexit only",
    "获取所有正在运行的模拟ID列表": "        List ids of all running simulations.",
    "Interview 功能": "Interview features",
    "检查模拟环境是否存活（可以接收Interview命令）": "        Check whether the sim environment is alive (accepts Interview commands).",
    "True 表示环境存活，False 表示环境已关闭": "            True when alive, False when closed",
    "获取模拟环境的详细状态信息": "        Get detailed environment status.",
    "状态详情字典，包含 status, twitter_available, reddit_available, timestamp": "            Status dict with status, twitter_available, reddit_available, timestamp",
    "采访单个Agent": "        Interview a single agent.",
    "prompt: 采访问题": "            prompt: interview question",
    "platform: 指定平台（可选）": "            platform: optional platform",
    "- 'twitter': 只采访Twitter平台": '                - "twitter": Twitter platform only',
    "- 'reddit': 只采访Reddit平台": '                - "reddit": Reddit platform only',
    "- None: 双平台模拟时同时采访两个平台，返回整合结果": "                - None: dual-platform runs interview both platforms and merge results",
    "timeout: 超时时间（秒）": "            timeout: seconds",
    "采访结果字典": "            Interview result dict.",
    "模拟不存在或环境未运行": "Simulation not found or environment not running",
    "TimeoutError: 等待响应超时": "            TimeoutError: response wait timed out",
    "模拟环境未运行或已关闭，无法执行Interview: {simulation_id}": "Environment not running; cannot interview: {simulation_id}",
    "发送Interview命令: simulation_id={simulation_id}, agent_id={agent_id}, platform={platform}": "Sending Interview command: simulation_id={simulation_id}, agent_id={agent_id}, platform={platform}",
    "批量采访多个Agent": "        Interview multiple agents in a batch.",
    "platform: 默认平台（可选，会被每个采访项的platform覆盖）": "            platform: default (overridden per interview item)",
    "- 'twitter': 默认只采访Twitter平台": '                - "twitter": Twitter platform only by default',
    "- 'reddit': 默认只采访Reddit平台": '                - "reddit": Reddit platform only by default',
    "- None: 双平台模拟时每个Agent同时采访两个平台": "                - None: dual-platform runs interview both platforms per agent",
    "批量采访结果字典": "            Batch interview result dict.",
    "发送批量Interview命令: simulation_id={simulation_id}, count={len(interviews)}, platform={platform}": "Sending batch Interview command: simulation_id={simulation_id}, count={len(interviews)}, platform={platform}",
    "采访所有Agent（全局采访）": "        Interview every agent (global interview).",
    "使用相同的问题采访模拟中的所有Agent": "        Asks every agent in the simulation the same question.",
    "prompt: 采访问题（所有Agent使用相同问题）": "            prompt: the question asked of all agents",
    "全局采访结果字典": "            Global interview result dict.",
    "从配置文件获取所有Agent信息": "        # load all agents from the config file",
    "模拟配置不存在: {simulation_id}": "Simulation config not found: {simulation_id}",
    "模拟配置中没有Agent: {simulation_id}": "No agents in simulation config: {simulation_id}",
    "构建批量采访列表": "        # build the batch interview list",
    "发送全局Interview命令: simulation_id={simulation_id}, agent_count={len(interviews)}, platform={platform}": "Sending global Interview command: simulation_id={simulation_id}, agent_count={len(interviews)}, platform={platform}",
    "关闭模拟环境（而不是停止模拟进程）": "        Close the simulation environment (not the runner process).",
    "向模拟发送关闭环境命令，使其优雅退出等待命令模式": "        Asks the sim to exit its wait-for-commands loop gracefully.",
    "操作结果字典": "            Operation result dict.",
    "环境已经关闭": "Environment already closed",
    "发送关闭环境命令: simulation_id={simulation_id}": "Sending close-environment command: simulation_id={simulation_id}",
    "环境关闭命令已发送": "Close-environment command sent",
    "超时可能是因为环境正在关闭": "            # a timeout may mean the environment is already closing",
    "环境关闭命令已发送（等待响应超时，环境可能正在关闭）": "Close-environment command sent (response wait timed out; environment may be closing)",
    "从单个数据库获取Interview历史": "Get Interview history from a single database.",
    "读取Interview历史失败 ({platform_name}): {e}": "Failed to read Interview history ({platform_name}): {e}",
    "获取Interview历史记录（从数据库读取）": "        Get Interview history (read from the databases).",
    "platform: 平台类型（reddit/twitter/None）": "            platform: platform type (reddit/twitter/None)",
    "- 'reddit': 只获取Reddit平台的历史": '                - "reddit": Reddit history only',
    "- 'twitter': 只获取Twitter平台的历史": '                - "twitter": Twitter history only',
    "- None: 获取两个平台的所有历史": "                - None: all history from both platforms",
    "agent_id: 指定Agent ID（可选，只获取该Agent的历史）": "            agent_id: optional; only that agent's history",
    "limit: 每个平台返回数量限制": "            limit: per-platform return cap",
    "Interview历史记录列表": "            List of Interview history records.",
    "确定要查询的平台": "        # decide which platforms to query",
    "不指定platform时，查询两个平台": "            # no platform given: query both",
    "按时间降序排序": "        # sort newest first",
    "如果查询了多个平台，限制总数": "        # cap the total when multiple platforms were queried",
}

keys = sorted(M.keys(), key=len, reverse=True)
lines = src.splitlines(keepends=True)
ok = miss = 0
for i, line in enumerate(lines):
    if not re.search(r"[\u4e00-\u9fff]", line):
        continue
    body = line.rstrip("\n")
    for zh in keys:
        if zh in body:
            body = body.replace(zh, M[zh])
            ok += 1
            break
    else:
        miss += 1
        print(f"MISS {i+1}: {body.strip()[:70]}")
    lines[i] = body + "\n"
open(P, "w", encoding="utf-8").write("".join(lines))
cjk = sum(1 for l in lines if re.search(r"[\u4e00-\u9fff]", l))
print(f"runner: {ok} ok, {miss} miss, {cjk} left")
