#!/usr/bin/env python3
"""One-shot English sweep for backend/app/services/zep_graph_memory_updater.py."""
import re

P = "backend/app/services/zep_graph_memory_updater.py"
src = open(P, encoding="utf-8").read()

M = {
    "Zep图谱记忆更新服务": "Zep graph memory update service",
    "将模拟中的Agent活动动态更新到Zep图谱中": "Streams agent activity from a simulation into the Zep graph.",
    "Agent活动记录": "One recorded agent activity.",
    "将活动转换为可以发送给Zep的文本描述": "        Convert the activity into a text description to send to Zep.",
    "采用自然语言描述格式，让Zep能够从中提取实体和关系": "        Natural-language format lets Zep extract entities and relations.",
    "不添加模拟相关的前缀，避免误导图谱更新": "        No simulation-specific prefix, to avoid skewing graph updates.",
    "# 根据不同的动作类型生成不同的描述": "        # per-action-type description",
    "发布了一条帖子：「{content}」": "posted: \"{content}\"",
    "发布了一条帖子": "made a post",
    "点赞帖子 - 包含帖子原文和作者信息": "        Like a post - includes the original text and author.",
    "点赞了{post_author}的帖子：「{post_content}」": "liked {post_author}'s post: \"{post_content}\"",
    "点赞了一条帖子：「{post_content}」": "liked a post: \"{post_content}\"",
    "点赞了{post_author}的一条帖子": "liked a post by {post_author}",
    "点赞了一条帖子": "liked a post",
    "踩帖子 - 包含帖子原文和作者信息": "        Dislike a post - includes the original text and author.",
    "踩了{post_author}的帖子：「{post_content}」": "disliked {post_author}'s post: \"{post_content}\"",
    "踩了一条帖子：「{post_content}」": "disliked a post: \"{post_content}\"",
    "踩了{post_author}的一条帖子": "disliked a post by {post_author}",
    "踩了一条帖子": "disliked a post",
    "转发帖子 - 包含原帖内容和作者信息": "        Repost - includes the original text and author.",
    "转发了{original_author}的帖子：「{original_content}」": "reposted {original_author}'s post: \"{original_content}\"",
    "转发了一条帖子：「{original_content}」": "reposted a post: \"{original_content}\"",
    "转发了{original_author}的一条帖子": "reposted a post by {original_author}",
    "转发了一条帖子": "reposted a post",
    "引用帖子 - 包含原帖内容、作者信息和引用评论": "        Quote post - includes the original text, author, and quote comment.",
    "引用了{original_author}的帖子「{original_content}」": "quoted {original_author}'s post \"{original_content}\"",
    "引用了一条帖子「{original_content}」": "quoted a post \"{original_content}\"",
    "引用了{original_author}的一条帖子": "quoted a post by {original_author}",
    "引用了一条帖子": "quoted a post",
    "，并评论道：「{quote_content}」": " and commented: \"{quote_content}\"",
    "关注用户 - 包含被关注用户的名称": "        Follow a user - includes the followed user's name.",
    "关注了用户「{target_user_name}」": "followed user \"{target_user_name}\"",
    "关注了一个用户": "followed a user",
    "发表评论 - 包含评论内容和所评论的帖子信息": "        Comment - includes the comment text and the post it replies to.",
    "在{post_author}的帖子「{post_content}」下评论道：「{content}」": "commented on {post_author}'s post \"{post_content}\": \"{content}\"",
    "在帖子「{post_content}」下评论道：「{content}」": "commented on the post \"{post_content}\": \"{content}\"",
    "在{post_author}的帖子下评论道：「{content}」": "commented on {post_author}'s post: \"{content}\"",
    "评论道：「{content}」": "commented: \"{content}\"",
    "发表了评论": "left a comment",
    "点赞评论 - 包含评论内容和作者信息": "        Like a comment - includes the comment text and author.",
    "点赞了{comment_author}的评论：「{comment_content}」": "liked {comment_author}'s comment: \"{comment_content}\"",
    "点赞了一条评论：「{comment_content}」": "liked a comment: \"{comment_content}\"",
    "点赞了{comment_author}的一条评论": "liked a comment by {comment_author}",
    "点赞了一条评论": "liked a comment",
    "踩评论 - 包含评论内容和作者信息": "        Dislike a comment - includes the comment text and author.",
    "踩了{comment_author}的评论：「{comment_content}」": "disliked {comment_author}'s comment: \"{comment_content}\"",
    "踩了一条评论：「{comment_content}」": "disliked a comment: \"{comment_content}\"",
    "踩了{comment_author}的一条评论": "disliked a comment by {comment_author}",
    "踩了一条评论": "disliked a comment",
    "搜索帖子 - 包含搜索关键词": "        Search posts - includes the search keywords.",
    "搜索了「{query}」": "searched for \"{query}\"",
    "进行了搜索": "performed a search",
    "搜索用户 - 包含搜索关键词": "        Search users - includes the search keywords.",
    "搜索了用户「{query}」": "searched for users \"{query}\"",
    "搜索了用户": "searched for users",
    "屏蔽用户 - 包含被屏蔽用户的名称": "        Mute a user - includes the muted user's name.",
    "屏蔽了用户「{target_user_name}」": "muted user \"{target_user_name}\"",
    "屏蔽了一个用户": "muted a user",
    "# 对于未知的动作类型，生成通用描述": "        # generic description for unknown action types",
    "执行了{self.action_type}操作": "performed a {self.action_type} action",
    "Zep图谱记忆更新器": "    Zep graph memory updater.",
    "监控模拟的actions日志文件，将新的agent活动实时更新到Zep图谱中。": "    Watches a simulation's actions log and streams new agent activity into the Zep graph in real time.",
    "按平台分组，每累积BATCH_SIZE条活动后批量发送到Zep。": "    Buffers per platform and batch-sends to Zep once BATCH_SIZE activities accumulate.",
    "所有有意义的行为都会被更新到Zep，action_args中会包含完整的上下文信息：": "    Every meaningful behavior is pushed to Zep; action_args carries full context:",
    "- 点赞/踩的帖子原文": "    - original text of liked/disliked posts",
    "- 转发/引用的帖子原文": "    - original text of reposted/quoted posts",
    "- 关注/屏蔽的用户名": "    - names of followed/muted users",
    "- 点赞/踩的评论原文": "    - original text of liked/disliked comments",
    "# 批量发送大小（每个平台累积多少条后发送）": "    # batch size (activities buffered per platform before sending)",
    "# 平台名称映射（用于控制台显示）": "    # platform display names (console output)",
    "'twitter': '世界1',": "'twitter': 'World 1 (Twitter)',",
    "'reddit': '世界2',": "'reddit': 'World 2 (Reddit)',",
    "# 发送间隔（秒），避免请求过快": "    # send interval (seconds) to avoid hammering the API",
    "初始化更新器": "        Initialize the updater.",
    "graph_id: Zep图谱ID": "            graph_id: Zep graph id",
    "api_key: Zep API Key（可选，默认从配置读取）": "            api_key: Zep API key (optional; defaults from config)",
    "ZEP_API_KEY未配置": "ZEP_API_KEY not configured",
    "# 活动队列": "        # activity queue",
    "# 按平台分组的活动缓冲区（每个平台各自累积到BATCH_SIZE后批量发送）": "        # per-platform buffers (each flushes at BATCH_SIZE)",
    "# 控制标志": "        # control flags",
    "# 统计": "        # counters",
    "实际添加到队列的活动数": "activities actually enqueued",
    "成功发送到Zep的批次数": "batches sent to Zep successfully",
    "成功发送到Zep的活动条数": "activities sent to Zep successfully",
    "发送失败的批次数": "batches that failed to send",
    "被过滤跳过的活动数（DO_NOTHING）": "activities skipped by filtering (DO_NOTHING)",
    "初始化完成: graph_id={graph_id}, batch_size={self.BATCH_SIZE}": "initialized: graph_id={graph_id}, batch_size={self.BATCH_SIZE}",
    "获取平台的显示名称": "        Get the display name for a platform.",
    "启动后台工作线程": "        Start the background worker thread.",
    "已启动: graph_id={self.graph_id}": "started: graph_id={self.graph_id}",
    "已停止: graph_id={self.graph_id}, ": "stopped: graph_id={self.graph_id}, ",
    "添加一个agent活动到队列": "        Enqueue one agent activity.",
    "所有有意义的行为都会被添加到队列，包括：": "        Every meaningful behavior is enqueued, including:",
    "- CREATE_POST（发帖）": "        - CREATE_POST (posting)",
    "- CREATE_COMMENT（评论）": "        - CREATE_COMMENT (commenting)",
    "- QUOTE_POST（引用帖子）": "        - QUOTE_POST (quote posting)",
    "- SEARCH_POSTS（搜索帖子）": "        - SEARCH_POSTS (post search)",
    "- SEARCH_USER（搜索用户）": "        - SEARCH_USER (user search)",
    "- LIKE_POST/DISLIKE_POST（点赞/踩帖子）": "        - LIKE_POST/DISLIKE_POST (liking/disliking posts)",
    "- REPOST（转发）": "        - REPOST (reposting)",
    "- FOLLOW（关注）": "        - FOLLOW (following)",
    "- MUTE（屏蔽）": "        - MUTE (muting)",
    "- LIKE_COMMENT/DISLIKE_COMMENT（点赞/踩评论）": "        - LIKE_COMMENT/DISLIKE_COMMENT (liking/disliking comments)",
    "action_args中会包含完整的上下文信息（如帖子原文、用户名等）。": "        action_args carries the full context (post text, usernames, ...).",
    "activity: Agent活动记录": "            activity: the agent activity record",
    "# 跳过DO_NOTHING类型的活动": "        # skip DO_NOTHING activities",
    "添加活动到Zep队列: {activity.agent_name} - {activity.action_type}": "Activity queued for Zep: {activity.agent_name} - {activity.action_type}",
    "从字典数据添加活动": "        Add an activity from dict data.",
    "data: 从actions.jsonl解析的字典数据": "            data: dict parsed from actions.jsonl",
    "platform: 平台名称 (twitter/reddit)": "            platform: platform name (twitter/reddit)",
    "# 跳过事件类型的条目": "        # skip event-type entries",
    "后台工作循环 - 按平台批量发送活动到Zep": "Background worker loop - batch-sends activities to Zep per platform.",
    "# 尝试从队列获取活动（超时1秒）": "                # pull an activity from the queue (1s timeout)",
    "# 将活动添加到对应平台的缓冲区": "                    # buffer it under its platform",
    "# 检查该平台是否达到批量大小": "                    # batch size reached for that platform?",
    "工作循环异常: {e}": "Worker loop error: {e}",
    "批量发送活动到Zep图谱（合并为一条文本）": "        Batch-send activities to the Zep graph (merged into one text).",
    "activities: Agent活动列表": "            activities: list of agent activities",
    "platform: 平台名称": "            platform: platform name",
    "成功批量发送 {len(payload_activities)} 条{display_name}活动到图谱 {self.graph_id}": "Batch-sent {len(payload_activities)} {display_name} activities to graph {self.graph_id}",
    "批量内容预览: {combined_text[:200]}...": "Batch content preview: {combined_text[:200]}...",
    "批量发送到Zep失败，未自动重放非幂等写入: {e}": "Batch send to Zep failed; non-idempotent writes NOT replayed: {e}",
    "发送队列和缓冲区中剩余的活动": "        Flush remaining queued and buffered activities.",
    "# 首先处理队列中剩余的活动，添加到缓冲区": "        # drain the queue into the buffers first",
    "发送{display_name}平台剩余的 {len(buffer)} 条活动": "Sending {len(buffer)} remaining {display_name} activities",
    "获取统计信息": "        Get statistics.",
    "添加到队列的活动总数": "total activities enqueued",
    "成功发送的批次数": "batches sent successfully",
    "成功发送的活动条数": "activities sent successfully",
    "各平台缓冲区大小": "per-platform buffer sizes",
    "管理多个模拟的Zep图谱记忆更新器": "    Manages Zep graph memory updaters across simulations.",
    "每个模拟可以有自己的更新器实例": "    Each simulation gets its own updater instance.",
    "为模拟创建图谱记忆更新器": "        Create the graph memory updater for a simulation.",
    "ZepGraphMemoryUpdater实例": "            The ZepGraphMemoryUpdater instance.",
    "# 如果已存在，先停止旧的": "            # stop the old one first if present",
    "创建图谱记忆更新器: simulation_id={simulation_id}, graph_id={graph_id}": "Created graph memory updater: simulation_id={simulation_id}, graph_id={graph_id}",
    "获取模拟的更新器": "        Get a simulation's updater.",
    "停止并移除模拟的更新器": "        Stop and remove a simulation's updater.",
    "已停止图谱记忆更新器: simulation_id={simulation_id}": "Stopped graph memory updater: simulation_id={simulation_id}",
    "# 防止 stop_all 重复调用的标志": "    # guard against duplicate stop_all calls",
    "停止所有更新器": "        Stop every updater.",
    "# 防止重复调用": "        # re-entry guard",
    "停止更新器失败: simulation_id=%s, error=%s": "Failed to stop updater: simulation_id=%s, error=%s",
    "部分图谱更新器未完整停止: {details}": "Some graph updaters did not stop cleanly: {details}",
    "已停止所有图谱记忆更新器": "All graph memory updaters stopped",
    "获取所有更新器的统计信息": "        Get statistics for every updater.",
}

keys = sorted(M.keys(), key=len, reverse=True)
lines = src.splitlines(keepends=True)
ok = miss = 0
for i, line in enumerate(lines):
    if not re.search(r"[\u4e00-\u9fff]", line):
        continue
    body = line.rstrip("\n")
    for zh in keys:
        if zh in body:
            body = body.replace(zh, M[zh])
            ok += 1
            break
    else:
        miss += 1
        print(f"MISS {i+1}: {body.strip()[:70]}")
    lines[i] = body + "\n"
open(P, "w", encoding="utf-8").write("".join(lines))
cjk = sum(1 for l in lines if re.search(r"[\u4e00-\u9fff]", l))
print(f"zgm: {ok} ok, {miss} miss, {cjk} left")
